AllCops:
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/enum-type.gemspec'
    - '**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FileName:
  Exclude:
    - '**/Rakefile'
    - '**/Gemfile'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*.rake'
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

